const YEARS=Array.from({length:12},(_,i)=>`mat_${2024+i}_${2025+i}`);const LABELS=YEARS.map(x=>x.replace('mat_','').replace('_','–'));
let data,agebData,limitData,map,markers=L.layerGroup(),agebLayer,limitLayer,subLayer,fractLayer,currentView='proyeccion',chart,filtered=[];
const $=id=>document.getElementById(id);const fmt=n=>Number(n||0).toLocaleString('es-MX');
function trend(v,b){const p=b?((v-b)/b)*100:0;return p>2?'up':p<-2?'down':'stable'}
function trendColor(t){return t==='up'?'#238b45':t==='down'?'#d73027':'#f0ad00'}
function attentionColor(c){const s=(c||'').toLowerCase();if(s.includes('muy alta'))return'#7f0000';if(s.includes('alta'))return'#d73027';if(s.includes('media'))return'#f0ad00';if(s.includes('baja')&&!s.includes('muy'))return'#91cf60';return'#1a9850'}
function hasValidPoint(f){const c=f&&f.geometry&&f.geometry.coordinates;return Array.isArray(c)&&c.length>=2&&Number.isFinite(Number(c[0]))&&Number.isFinite(Number(c[1]))}
Promise.all(['data/planteles_xochimilco.json','data/ageb_xochimilco.json','data/limite_xochimilco.json'].map(x=>fetch(x).then(r=>{if(!r.ok)throw new Error(`${x}: HTTP ${r.status}`);return r.json()}))).then(([a,b,c])=>{data=a;agebData=b;limitData=c;init()}).catch(e=>alert('No se pudieron cargar los datos: '+e));
function init(){map=L.map('map',{zoomControl:true}).setView([19.28,-99.17],11);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);markers.addTo(map);limitLayer=L.geoJSON(limitData,{style:{color:'#173f5f',weight:3,fill:false}}).addTo(map);agebLayer=L.geoJSON(agebData,{style:agebStyle,onEachFeature:(f,l)=>l.bindTooltip('AGEB '+f.properties.CVE_AGEB)}).addTo(map);map.fitBounds(limitLayer.getBounds());
 const feats=(data.features||[]).filter(hasValidPoint);data.features=feats;[...new Set(feats.map(f=>f.properties.nivel).filter(Boolean))].sort().forEach(v=>$('nivel').add(new Option(v,v)));[...new Set(feats.map(f=>f.properties.atencion_clase).filter(Boolean))].sort().forEach(v=>$('attention').add(new Option(v,v)));[...new Set(feats.flatMap(f=>Array.isArray(f.properties.programas)?f.properties.programas:[]))].sort().forEach(v=>$('program').add(new Option(v,v)));YEARS.forEach((v,i)=>$('year').add(new Option(LABELS[i],v)));$('year').value='mat_2035_2036';bind();render();}
function bind(){['search','nivel','year','trend','attention','program'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',render));document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('clear').onclick=()=>{['search','nivel','trend','attention','program'].forEach(id=>$(id).value='');$('year').value='mat_2035_2036';render()};$('agebToggle').onchange=()=>$('agebToggle').checked?agebLayer.addTo(map):map.removeLayer(agebLayer);$('subToggle').onchange=toggleSub;$('fractToggle').onchange=toggleFract;$('download').onclick=downloadCSV;$('closeDetail').onclick=()=>$('detail').classList.add('hidden');$('menuBtn').onclick=()=>$('panel').classList.toggle('open')}
function switchView(v){currentView=v;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('projectionControls').classList.toggle('hidden',v!=='proyeccion');$('infraControls').classList.toggle('hidden',v!=='infraestructura');if(v==='infraestructura'&&map.hasLayer(agebLayer))map.removeLayer(agebLayer);if(v==='proyeccion'&&$('agebToggle').checked)agebLayer.addTo(map);render()}
function agebStyle(f){const y=$('year')?.value||'mat_2035_2036',b=f.properties.mat_2024_2025||0,v=f.properties[y]||0,t=trend(v,b);return{color:'#777',weight:.4,fillColor:trendColor(t),fillOpacity:.22}}
function render(){if(!data)return;const q=$('search').value.trim().toLowerCase(),year=$('year').value;filtered=data.features.filter(f=>{const p=f.properties;const hay=[p.inmueble,p.idinmueble,...(Array.isArray(p.ccts)?p.ccts:[])].join(' ').toLowerCase();if(q&&!hay.includes(q))return false;if($('nivel').value&&p.nivel!==$('nivel').value)return false;if(currentView==='proyeccion'&&$('trend').value&&trend(p.proyecciones[year],p.proyecciones.mat_2024_2025)!=$('trend').value)return false;if(currentView==='infraestructura'&&$('attention').value&&p.atencion_clase!==$('attention').value)return false;if(currentView==='infraestructura'&&$('program').value&&!(Array.isArray(p.programas)?p.programas:[]).includes($('program').value))return false;return true});markers.clearLayers();filtered.filter(hasValidPoint).forEach(f=>{const p=f.properties,val=currentView==='proyeccion'?trendColor(trend(p.proyecciones[year],p.proyecciones.mat_2024_2025)):attentionColor(p.atencion_clase);const m=L.circleMarker([f.geometry.coordinates[1],f.geometry.coordinates[0]],{radius:7,color:'#fff',weight:1.5,fillColor:val,fillOpacity:.95});m.bindPopup(popup(p,year));m.on('click',()=>detail(p));m.addTo(markers)});if(agebLayer&&map.hasLayer(agebLayer))agebLayer.setStyle(agebStyle);stats(year);legend()}
function popup(p,y){return `<div class="popup-title">${p.inmueble}</div><div>${(Array.isArray(p.ccts)?p.ccts:[]).join(', ')}</div>${currentView==='proyeccion'?`<div class="metric">Matrícula ${y.replace('mat_','').replace('_','–')}: <b>${fmt(p.proyecciones[y])}</b><br>Cambio desde 2024–2025: <b>${p.proyecciones[y]-p.proyecciones.mat_2024_2025}</b></div>`:`<div class="metric">Atención: <b>${p.atencion_clase}</b><br>Necesidades: <b>${p.total_necesidades}</b></div>`}`}
function detail(p){$('detail').classList.remove('hidden');let html=`<h2>${p.inmueble}</h2><div>${p.nivel||''} · ID ${p.idinmueble}</div><p>${(Array.isArray(p.ccts)?p.ccts:[]).map(x=>`<span class="badge">${x}</span>`).join('')}</p><h3>Proyección de matrícula</h3><table>${YEARS.map((y,i)=>`<tr><td>${LABELS[i]}</td><td><b>${fmt(p.proyecciones[y])}</b></td></tr>`).join('')}</table><h3>Infraestructura</h3><table><tr><td>Índice de mantenimiento</td><td><b>${p.indice_mantenimiento}</b></td></tr><tr><td>Atención de revisión</td><td><b>${p.atencion_clase}</b></td></tr><tr><td>Subsidencia</td><td><b>${p.subsidencia_clase}</b></td></tr><tr><td>Distancia a fractura</td><td><b>${fmt(p.dist_fractura_m)} m</b></td></tr></table><h3>Necesidades (${p.total_necesidades})</h3><ul>${(Array.isArray(p.necesidades)?p.necesidades:[]).map(x=>`<li>${x}</li>`).join('')||'<li>Sin necesidades registradas</li>'}</ul><h3>Programas e intervenciones</h3><ul>${(Array.isArray(p.programas)?p.programas:[]).map(x=>`<li>${x}</li>`).join('')||'<li>Sin intervención registrada</li>'}</ul>`;$('detailContent').innerHTML=html;if(chart)chart.destroy();chart=new Chart($('chart'),{type:'line',data:{labels:LABELS,datasets:[{label:'Matrícula',data:YEARS.map(y=>p.proyecciones[y]),borderWidth:2,tension:.2}]},options:{plugins:{legend:{display:false}},scales:{y:{beginAtZero:false}}}})}
function stats(y){const base=filtered.reduce((s,f)=>s+(f.properties.proyecciones.mat_2024_2025||0),0),val=filtered.reduce((s,f)=>s+(f.properties.proyecciones[y]||0),0),change=val-base,pct=base?change/base*100:0;$('stats').innerHTML=`<div class="stat"><small>Inmuebles</small><b>${filtered.length}</b></div><div class="stat"><small>CCT</small><b>${new Set(filtered.flatMap(f=>Array.isArray(f.properties.ccts)?f.properties.ccts:[])).size}</b></div><div class="stat"><small>Matrícula base</small><b>${fmt(base)}</b></div><div class="stat"><small>Variación</small><b>${change>0?'+':''}${fmt(change)}</b><small>${pct.toFixed(1)}%</small></div>`}
function legend(){$('legend').innerHTML=currentView==='proyeccion'?'<div><span class="dot" style="background:#238b45"></span>Crecimiento &gt; 2%</div><div><span class="dot" style="background:#f0ad00"></span>Estabilidad ±2%</div><div><span class="dot" style="background:#d73027"></span>Disminución &lt; -2%</div>':'<div><span class="dot" style="background:#1a9850"></span>Muy baja</div><div><span class="dot" style="background:#91cf60"></span>Baja</div><div><span class="dot" style="background:#f0ad00"></span>Media</div><div><span class="dot" style="background:#d73027"></span>Alta</div><div><span class="dot" style="background:#7f0000"></span>Muy alta</div>'}
function toggleSub(){if(!$('subToggle').checked){if(subLayer)map.removeLayer(subLayer);return}if(subLayer){subLayer.addTo(map);return}fetch('data/subsidencias.json').then(r=>{if(!r.ok)throw new Error(`subsidencias.json: HTTP ${r.status}`);return r.json()}).then(d=>{subLayer=L.geoJSON(d,{style:f=>({color:'transparent',fillColor:['#1a9850','#91cf60','#fee08b','#f46d43','#d73027'][(f.properties.gridcode||1)-1]||'#999',fillOpacity:.35,weight:0})}).addTo(map)})}
function toggleFract(){if(!$('fractToggle').checked){if(fractLayer)map.removeLayer(fractLayer);return}if(fractLayer){fractLayer.addTo(map);return}fetch('data/fracturamiento.json').then(r=>{if(!r.ok)throw new Error(`fracturamiento.json: HTTP ${r.status}`);return r.json()}).then(d=>{fractLayer=L.geoJSON(d,{style:{color:'#8e44ad',weight:2,opacity:.8}}).addTo(map)})}
function downloadCSV(){const y=$('year').value;const rows=[['idinmueble','inmueble','nivel','cct','matricula_base',y,'variacion','atencion','total_necesidades','programas']];filtered.filter(hasValidPoint).forEach(f=>{const p=f.properties;(Array.isArray(p.ccts)?p.ccts:[]).forEach(c=>rows.push([p.idinmueble,p.inmueble,p.nivel,c,p.proyecciones.mat_2024_2025,p.proyecciones[y],p.proyecciones[y]-p.proyecciones.mat_2024_2025,p.atencion_clase,p.total_necesidades,(Array.isArray(p.programas)?p.programas:[]).join('; ')]))});const csv=rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download='visor_xochimilco_filtrado.csv';a.click()}
