const PATHS={schools:'data/infraestructura_educativa_2026.json',programs:'data/programas_integradores.json',maintenance:'data/mantenimiento.json',reinforcement:'data/reforzamiento.json',famPotenciado:'data/fam_potenciado_2025.json',fam2026:'data/fam_potenciado_basico_2026.json',alcaldia:'data/beneficiadas_alcaldia_iztapalapa.json'};
const CCT_FIELDS=['cct1','cct2','cct3','cct4'];
const NEEDS=['impermeabi','interior','exterior1','loseta','ventanas','ventanas1','ventanas2','puertas','escaleras','pluviales','techos','desazolve','deterioro','concreto','tinacos','cisterna','agua','agua1','hidrosanit','sanitarios','luminarias','electrica','transforma','lamina'];
const IMPROVEMENT_LABELS={fam_regular:'FAM Regular 2025',programa_123_2025:'1, 2, 3 por mi Escuela 2025',fam_potenciado:'FAM Potenciado 2025',fam_potenciado_basico_2026:'FAM Potenciado + FAM Básico 2026',fam_reforzamiento:'FAM Reforzamiento estructural',programa_123_2026:'1, 2, 3 por mi Escuela 2026',alcaldia_apoyo:'Intervención de Alcaldía',ambas:'Con mantenimiento y reforzamiento'};
let schools=[],catalog=new Map(),state={};
document.addEventListener('DOMContentLoaded',init);

async function init(){
  const keys=Object.keys(PATHS); const values=await Promise.all(keys.map(key=>fetchJson(PATHS[key]))); const data=Object.fromEntries(keys.map((key,index)=>[key,values[index]]));
  schools=(data.schools.features||[]).map((feature,index)=>normalizeSchool(feature.properties||{},feature.geometry?.coordinates||[],index,false)).filter(Boolean);
  mergeProgramOnly(schools,data.programs); joinPrograms(schools,data.programs); joinImprovements(schools,data);
  buildCatalog(data.programs); populateFilters(); bindUI(); restoreState(); applyStats();
}
async function fetchJson(path){const response=await fetch(path,{cache:'no-store'});if(!response.ok)throw new Error(path);return response.json()}
function normalizeSchool(p,coords,index,programOnly){const lon=Number(coords[0]??p.lon),lat=Number(coords[1]??p.lat);if(!Number.isFinite(lon)||!Number.isFinite(lat))return null;const needs=NEEDS.filter(field=>Number(p[field])===1),indice=Number.isFinite(Number(p.Indice_Man))?Number(p.Indice_Man):needs.length;return{nombre:clean(p.inmueble||p.nombre)||'Escuela sin nombre',alcaldia:clean(p.alcaldia).toLocaleUpperCase('es-MX'),nivel:clean(p.principal||p.nivel),ccts:(programOnly?[p.cct]:CCT_FIELDS.map(field=>p[field])).map(cct).filter(Boolean),needs,indice,clasificacion:classify(indice),subsidencia:Number(p.subsidencia_nivel)||null,distFractura:Number.isFinite(Number(p.dist_fractura_m))?Number(p.dist_fractura_m):null,programOnly,programs:[],improvements:{},reinforcement:null}}
function mergeProgramOnly(list,rows){const known=new Set(list.flatMap(s=>s.ccts)),missing=new Map();rows.forEach(row=>{if(!known.has(row.cct)&&!missing.has(row.cct))missing.set(row.cct,row)});missing.forEach(row=>{const school=normalizeSchool({cct:row.cct,nombre:row.nombre,alcaldia:row.alcaldia,nivel:row.nivel,lon:row.lon,lat:row.lat},[],row.cct,true);if(school)list.push(school)})}
function joinPrograms(list,rows){const index=new Map();rows.forEach(row=>{if(!index.has(row.cct))index.set(row.cct,[]);index.get(row.cct).push(row)});list.forEach(s=>{const unique=new Map();s.ccts.flatMap(value=>index.get(value)||[]).forEach(row=>unique.set(`${row.cct}|${row.proyecto_id}`,row));s.programs=[...unique.values()]})}
function joinImprovements(list,data){const map=rows=>new Map(rows.map(row=>[cct(row.cct),row]));const mm=map(data.maintenance),rr=map(data.reinforcement),fp=map(data.famPotenciado),f26=map(data.fam2026),aa=map(data.alcaldia);const p25=new Set(data.programs.filter(row=>norm(row.programa)==='1 2 3 por mi escuela'&&row.proyecto.includes('(2025)')).map(row=>row.cct)),p26=new Set(data.programs.filter(row=>norm(row.programa)==='1 2 3 por mi escuela'&&row.proyecto.includes('(2026)')).map(row=>row.cct));list.forEach(s=>{const first=index=>s.ccts.map(value=>index.get(value)).find(Boolean)||null;const maintenance=first(mm),reinforcement=first(rr);s.reinforcement=reinforcement;s.improvements={fam_regular:Boolean(maintenance&&norm(maintenance.responsable).includes('ilife')),programa_123_2025:s.ccts.some(value=>p25.has(value)),fam_potenciado:Boolean(first(fp)),fam_potenciado_basico_2026:Boolean(first(f26)),fam_reforzamiento:Boolean(reinforcement),programa_123_2026:s.ccts.some(value=>p26.has(value)),alcaldia_apoyo:Boolean(first(aa)),ambas:Boolean(maintenance&&reinforcement)}})}
function buildCatalog(rows){rows.forEach(row=>{if(!catalog.has(row.proyecto_id))catalog.set(row.proyecto_id,row.proyecto)})}
function populateFilters(){fill('stAlcaldia',unique(schools.map(s=>s.alcaldia)));fill('stNivel',unique(schools.map(s=>s.nivel)))}
function fill(id,values){const select=q(id),first=select.querySelector('option').outerHTML;select.innerHTML=first+values.map(value=>`<option value="${esc(value)}">${esc(value)}</option>`).join('')}
function bindUI(){['stAlcaldia','stNivel'].forEach(id=>q(id).onchange=applyStats);['stCCT','stNombre'].forEach(id=>q(id).oninput=applyStats);q('stLimpiar').onclick=()=>{q('stAlcaldia').value='';q('stNivel').value='';q('stCCT').value='';q('stNombre').value='';applyStats()}}
function restoreState(){try{state=JSON.parse(localStorage.getItem('visorStateV3:Visor_Xochimilco')||'{}')}catch{state={}}q('stAlcaldia').value=state.alcaldia||'';q('stNivel').value=state.nivel||''}
function applyStats(){const a=q('stAlcaldia').value,n=q('stNivel').value,termCct=cct(q('stCCT').value),name=norm(q('stNombre').value),needs=state.needs||[],improvements=state.improvements||[],projects=state.projects||[],risk=state.risk||'';const result=schools.filter(s=>{if(a&&s.alcaldia!==a)return false;if(n&&s.nivel!==n)return false;if(termCct&&!s.ccts.some(value=>value.includes(termCct)))return false;if(name&&!norm(s.nombre).includes(name))return false;if(s.programOnly&&!projects.length)return false;if(needs.length&&!needs.every(field=>s.needs.includes(field)))return false;if(improvements.length&&!improvements.some(key=>s.improvements[key]))return false;if(projects.length&&!s.programs.some(row=>projects.includes(row.proyecto_id)))return false;if(risk==='obs_fractura'&&!(s.distFractura!==null&&s.distFractura<=250))return false;if(risk==='obs_subsidencia'&&!(s.subsidencia>=4))return false;if(risk==='obs_combinada'&&!((s.distFractura!==null&&s.distFractura<=250)&&s.subsidencia>=4))return false;return true});render(result,{needs,improvements,projects,risk})}
function render(rows,selection){q('stTotal').textContent=rows.length.toLocaleString('es-MX');q('stMax').textContent=rows.length?Math.max(...rows.map(s=>s.indice)):0;q('stAux1').textContent=unique(rows.map(s=>s.alcaldia)).length;q('stAux2').textContent=rows.length?(rows.reduce((sum,s)=>sum+s.indice,0)/rows.length).toFixed(1):'0.0';const tags=[];selection.projects.forEach(id=>tags.push(catalog.get(id)||id));selection.improvements.forEach(key=>tags.push(IMPROVEMENT_LABELS[key]||key));if(selection.needs.length)tags.push(`${selection.needs.length} variable(s) de mantenimiento`);if(selection.risk)tags.push('Observación territorial');q('statsContext').textContent=tags.length?'Se aplicó el cruce guardado desde el mapa.':'No hay cruces temáticos activos; se muestra la base general.';q('statsTags').innerHTML=tags.map(text=>`<span class="mini-tag blue">${esc(text)}</span>`).join('');renderDistribution(rows);renderGrouped(rows,'nivel','tablaNivel',false);renderGrouped(rows,'alcaldia','tablaAlcaldia',true);renderRanking(rows)}
function renderDistribution(rows){const classes=['Muy baja','Baja','Media','Alta','Muy alta'];q('tablaDistribucion').innerHTML=classes.map(label=>{const count=rows.filter(s=>s.clasificacion===label).length;return`<tr><td>${label}</td><td>${count.toLocaleString('es-MX')}</td><td>${pct(count,rows.length)}%<div class="bar"><span style="width:${pct(count,rows.length)}%"></span></div></td></tr>`}).join('')}
function renderGrouped(rows,field,target,full){const groups={};rows.forEach(s=>(groups[s[field]||'No registrado']??=[]).push(s));const result=Object.entries(groups).map(([name,list])=>({name,total:list.length,max:Math.max(...list.map(s=>s.indice)),ref:list.filter(s=>s.reinforcement).length})).sort((a,b)=>b.total-a.total);q(target).innerHTML=result.length?result.map(r=>full?`<tr><td>${esc(r.name)}</td><td>${r.total}</td><td>${r.max}</td><td>${r.ref}</td><td>${pct(r.total,rows.length)}%</td></tr>`:`<tr><td>${esc(r.name)}</td><td>${r.total}</td><td>${r.max}</td></tr>`).join(''):`<tr><td colspan="${full?5:3}" class="empty-row">No hay resultados.</td></tr>`}
function renderRanking(rows){q('tablaRanking').innerHTML=rows.length?[...rows].sort((a,b)=>b.indice-a.indice||a.nombre.localeCompare(b.nombre,'es')).slice(0,250).map((s,index)=>`<tr><td>${index+1}</td><td>${esc(s.nombre)}</td><td>${esc(s.ccts.join(', '))}</td><td>${esc(s.alcaldia)}</td><td>${esc(s.nivel)}</td><td><strong>${s.indice}</strong></td><td>${esc(unique(s.programs.map(row=>row.proyecto)).join(' · ')||'—')}</td></tr>`).join(''):'<tr><td colspan="7" class="empty-row">No hay resultados.</td></tr>'}
function classify(value){return value>=20?'Muy alta':value>=15?'Alta':value>=10?'Media':value>=5?'Baja':'Muy baja'}
function pct(a,b){return b?(a/b*100).toFixed(1):'0.0'}function cct(value){return clean(value).replace(/\s+/g,'').toUpperCase()}function clean(value){return value===null||value===undefined?'':String(value).trim().replace(/\s+/g,' ')}function norm(value){return clean(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}function unique(values){return[...new Set(values.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'))}function q(id){return document.getElementById(id)}function esc(value){return clean(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]))}
